title: UoBD Important Websites
show_downloads: false
safe: true
url: https://index.uobd.zning.me
enforce_ssl: index.uobd.zning.me
timezone: Asia/Dubai
author: ZNing

plugins:
  - jekyll-feed

google_analytics: G-MTYH758FNF
