title: UoBD Important Websites
show_downloads: false
safe: true
url: https://uobd.inology.tech
enforce_ssl: uobd.inology.tech
timezone: Asia/Dubai
author: ZNing

plugins:
  - jekyll-feed

google_analytics: G-MTYH758FNF
